// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9qqUiPO__Wz57lh76K7d4DrZw31APHIM',
    appId: '1:784151565290:android:9955b536ea7baa8782d893',
    messagingSenderId: '784151565290',
    projectId: 'pump-681ff',
    storageBucket: 'pump-681ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlzerGM1Pzm5X-Jbfho_Tn4hB0qeJUSuI',
    appId: '1:784151565290:ios:6d8064527517f9d582d893',
    messagingSenderId: '784151565290',
    projectId: 'pump-681ff',
    storageBucket: 'pump-681ff.appspot.com',
    androidClientId: '784151565290-33e6mu5outqh5bgu7hj73h3u2tokjq5h.apps.googleusercontent.com',
    iosClientId: '784151565290-o7a2uaus7g7kkv8ej2ign38k6le4tpkp.apps.googleusercontent.com',
    iosBundleId: 'br.com.pump',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlzerGM1Pzm5X-Jbfho_Tn4hB0qeJUSuI',
    appId: '1:784151565290:ios:6d8064527517f9d582d893',
    messagingSenderId: '784151565290',
    projectId: 'pump-681ff',
    storageBucket: 'pump-681ff.appspot.com',
    androidClientId: '784151565290-33e6mu5outqh5bgu7hj73h3u2tokjq5h.apps.googleusercontent.com',
    iosClientId: '784151565290-o7a2uaus7g7kkv8ej2ign38k6le4tpkp.apps.googleusercontent.com',
    iosBundleId: 'br.com.pump',
  );

}