name: flutter_flow
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  from_css_color: 2.0.0
  flutter_animate: 4.1.1+1
  fl_chart: 0.55.0
  font_awesome_flutter: 10.1.0
  dropdown_button2: 2.0.0
  provider: 6.0.4
  google_fonts: 4.0.3
  shared_preferences: 2.0.15
  shared_preferences_android: 2.1.0
  shared_preferences_ios: 2.1.1
  shared_preferences_platform_interface: 2.2.0
  shared_preferences_web: 2.1.0
  stop_watch_timer: 1.5.0
  json_path: 0.4.1
  timeago: 3.2.2
  url_launcher: 6.1.10
  url_launcher_android: 6.0.27
  url_launcher_ios: 6.1.4
  url_launcher_platform_interface: 2.1.2
  page_transition: 2.0.4
  video_player: 2.6.0
  video_player_android: 2.4.3
  video_player_avfoundation: 2.4.2
  video_player_platform_interface: 6.1.0
  video_player_web: 2.0.15
  chewie: 1.4.0
  auto_size_text: 3.0.0
  file_picker: 5.2.6
  image_picker: ^1.0.7
  image_picker_android: ^0.8.7
  image_picker_for_web: 2.2.0
  image_picker_ios: ^0.8.8
  image_picker_platform_interface: ^2.8.0
  mime_type: 1.0.0
  intl: 0.18.0
  go_router: 7.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
