name: pump_activity
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: 7.1.1
  cached_network_image: ^3.2.3
  expandable: 5.0.1
  intl: 0.18.0
  flutter_animate: 4.1.1+1
  fl_chart: 0.55.0
  auto_size_text: 3.0.0
  flutter_flow:
    path: ../flutter_flow
  api_manager:
    path: ../api_manager
  pump_components:
    path: ../pump_components

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
