Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8
source "https://rubygems.org"
gem "xcpretty"
gem "slather", "2.6.1"
gem "cocoapods", "1.10.2"
gem "fastlane", "2.219.0"
gem "xcode-install"
gem "dotenv"